# Generated by Django 5.1.1 on 2024-09-07 18:55

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='E-mail')),
                ('tipo_usuario', models.CharField(choices=[('GESTOR', 'Gestor'), ('CLIENTE', 'Cliente'), ('ASSOCIADO', 'Associado')], default='CLIENTE', max_length=20, verbose_name='Tipo Usuário')),
                ('nome_sobrenome', models.CharField(max_length=60, verbose_name='Nome Sobrenome')),
                ('telefone', models.CharField(max_length=15, verbose_name='Telefone')),
                ('cidade', models.CharField(blank=True, max_length=80, null=True, verbose_name='Cidade')),
                ('estado', models.CharField(blank=True, max_length=25, null=True, verbose_name='Estado')),
                ('foto', models.ImageField(blank=True, default='usuario-padrao.png', null=True, upload_to='foto/%Y/%m/%d', verbose_name='Foto')),
                ('hash_cliente', models.CharField(blank=True, max_length=36, null=True, verbose_name='Hash Cliente')),
                ('hash_usuario', models.CharField(default=uuid.uuid4, max_length=36, verbose_name='Hash Usuário')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Usuário',
                'verbose_name_plural': 'Usuários',
            },
        ),
    ]
