# Generated by Django 5.1.1 on 2024-09-11 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='tipo_usuario',
            field=models.CharField(choices=[('GESTOR', 'Gestor'), ('CLIENTE', 'Cliente'), ('ASSOCIADO', 'Associado')], max_length=20, verbose_name='Tipo Usuário'),
        ),
    ]
