# Generated by Django 5.1.1 on 2024-10-11 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0006_alter_usuario_groups_alter_usuario_user_permissions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='hash_cliente',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='hash_usuario',
        ),
        migrations.AddField(
            model_name='usuario',
            name='bloco',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='quadra',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
