# Generated by Django 5.1.1 on 2024-10-15 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0007_remove_usuario_hash_cliente_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='quadra',
            new_name='unidade',
        ),
    ]
