# Generated by Django 5.1.1 on 2024-09-11 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empreendimentos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empreendimento',
            name='estagio',
            field=models.CharField(choices=[('OBRNAOINICIADA', 'Obras não iniciadas'), ('OBREMANDAMENTO', 'Obras em andamento'), ('OBRFINALIZADAS', 'Obras finalizadas')], default='OBRNAOINICIADA', max_length=20),
        ),
    ]
