# Generated by Django 5.1.1 on 2024-09-16 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empreendimentos', '0003_alter_empreendimento_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='empreendimento',
            name='link_google_maps',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
