# Generated by Django 5.1.1 on 2024-09-18 17:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empreendimentos', '0006_rename_imovel_fotoempreendimento_empreendimento'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentoEmpreendimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.ImageField(blank=True, null=True, upload_to='empreendimento/documento/')),
                ('empreendimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empreendimentos.empreendimento', verbose_name='Empreendimento')),
            ],
            options={
                'verbose_name': 'Documento Empreendimento',
                'verbose_name_plural': 'Documentos Empreendimentos',
            },
        ),
    ]
