# Generated by Django 4.0 on 2024-09-19 10:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('empreendimentos', '0008_alter_documentoempreendimento_arquivo'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentoempreendimento',
            name='nome_arquivo',
            field=models.CharField(default='', max_length=60),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='AndamentoObra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(choices=[('AGUAPOTAVEL', 'Água Potável'), ('ENERGIAILUMINACAO', 'Energia e Iluminação'), ('DRENAGEM', 'Drenagem'), ('ALVENARIA', 'Alvenaria'), ('ACABAMENTO', 'Acabamento')], default='AGUAPOTAVEL', max_length=20)),
                ('porcentagem', models.IntegerField(default=1, verbose_name='Porcentagem')),
                ('exibir_site', models.BooleanField(default=True, verbose_name='Exibir no Site?')),
                ('empreendimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empreendimentos.empreendimento', verbose_name='Empreendimento')),
            ],
            options={
                'verbose_name': 'Andamento da Obra',
                'verbose_name_plural': 'Andamentos das Obras',
            },
        ),
    ]
