# Generated by Django 5.1.1 on 2024-09-25 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empreendimentos', '0009_documentoempreendimento_nome_arquivo_andamentoobra'),
    ]

    operations = [
        migrations.AddField(
            model_name='empreendimento',
            name='exibe_agua_potavel',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='empreendimento',
            name='exibe_drenagem',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='empreendimento',
            name='exibe_energia_iluminacao',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='empreendimento',
            name='exibe_esgoto_sanitario',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='empreendimento',
            name='exibe_habitacao',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='empreendimento',
            name='exibe_paisagismo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='empreendimento',
            name='exibe_pavimentacao',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='empreendimento',
            name='exibe_terraplanagem',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='empreendimento',
            name='parcentual_drenagem',
            field=models.CharField(default='', max_length=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='empreendimento',
            name='parcentual_habitacao',
            field=models.CharField(default='', max_length=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='empreendimento',
            name='parcentual_paisagismo',
            field=models.CharField(default='', max_length=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='empreendimento',
            name='parcentual_pavimentacao',
            field=models.CharField(default='', max_length=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='empreendimento',
            name='parcentual_terraplanagem',
            field=models.CharField(default='', max_length=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='empreendimento',
            name='percentual_agua_potavel',
            field=models.CharField(default='', max_length=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='empreendimento',
            name='percentual_energia_iluminacao',
            field=models.CharField(default='', max_length=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='empreendimento',
            name='percentual_esgoto_sanitario',
            field=models.CharField(default='', max_length=3),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='AndamentoObra',
        ),
    ]
