# Generated by Django 5.1.1 on 2024-09-25 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empreendimentos', '0010_empreendimento_exibe_agua_potavel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empreendimento',
            name='parcentual_drenagem',
            field=models.CharField(default=0, max_length=3),
        ),
        migrations.AlterField(
            model_name='empreendimento',
            name='parcentual_habitacao',
            field=models.CharField(default=0, max_length=3),
        ),
        migrations.AlterField(
            model_name='empreendimento',
            name='parcentual_paisagismo',
            field=models.CharField(default=0, max_length=3),
        ),
        migrations.AlterField(
            model_name='empreendimento',
            name='parcentual_pavimentacao',
            field=models.CharField(default=0, max_length=3),
        ),
        migrations.AlterField(
            model_name='empreendimento',
            name='parcentual_terraplanagem',
            field=models.CharField(default=0, max_length=3),
        ),
        migrations.AlterField(
            model_name='empreendimento',
            name='percentual_agua_potavel',
            field=models.CharField(default=0, max_length=3),
        ),
        migrations.AlterField(
            model_name='empreendimento',
            name='percentual_energia_iluminacao',
            field=models.CharField(default=0, max_length=3),
        ),
        migrations.AlterField(
            model_name='empreendimento',
            name='percentual_esgoto_sanitario',
            field=models.CharField(default=0, max_length=3),
        ),
    ]
