# Generated by Django 5.1.1 on 2024-09-25 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empreendimentos', '0011_alter_empreendimento_parcentual_drenagem_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='empreendimento',
            old_name='parcentual_drenagem',
            new_name='percentual_drenagem',
        ),
        migrations.RenameField(
            model_name='empreendimento',
            old_name='parcentual_habitacao',
            new_name='percentual_habitacao',
        ),
        migrations.RenameField(
            model_name='empreendimento',
            old_name='parcentual_paisagismo',
            new_name='percentual_paisagismo',
        ),
        migrations.RenameField(
            model_name='empreendimento',
            old_name='parcentual_pavimentacao',
            new_name='percentual_pavimentacao',
        ),
        migrations.RenameField(
            model_name='empreendimento',
            old_name='parcentual_terraplanagem',
            new_name='percentual_terraplanagem',
        ),
    ]
