# Generated by Django 5.1.1 on 2024-10-11 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empreendimentos', '0012_rename_parcentual_drenagem_empreendimento_percentual_drenagem_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='empreendimento',
            name='quantidade_blocos',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='empreendimento',
            name='quantidade_quadras',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
