# Generated by Django 5.1.1 on 2024-11-05 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empreendimentos', '0015_fotoandamentoobra'),
    ]

    operations = [
        migrations.AddField(
            model_name='empreendimento',
            name='unidades_disponiveis',
            field=models.IntegerField(default=0),
        ),
    ]
