# Generated by Django 5.1.1 on 2024-11-05 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empreendimentos', '0016_empreendimento_unidades_disponiveis'),
    ]

    operations = [
        migrations.AddField(
            model_name='empreendimento',
            name='cep',
            field=models.CharField(blank=True, max_length=9, null=True),
        ),
    ]
