# Generated by Django 5.1.1 on 2024-11-06 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empreendimentos', '0017_empreendimento_cep'),
    ]

    operations = [
        migrations.AddField(
            model_name='empreendimento',
            name='visivel',
            field=models.BooleanField(default=False),
        ),
    ]
